name: marian-hub
type: typo3
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
database:
  type: mariadb
  version: "10.11"
composer_version: "2"
web_environment:
  - TYPO3_CONTEXT=Development
  - TYPO3_DB_DRIVER=mysqli
  - TYPO3_DB_HOST=db
  - TYPO3_DB_NAME=db
  - TYPO3_DB_USERNAME=db
  - TYPO3_DB_PASSWORD=db
  - TYPO3_DB_PORT=3306
hooks:
  post-start:
    - exec: composer install --no-interaction
